dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
stages:
  - lint
branches:
  - master
  - Development


jobs:
  include:
    stage: lint
    script:
      - "pylint ./scripts"


